apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-default-namespace
  namespace: default
spec:
  podSelector: {}  # This applies to all pods in the 'default' namespace
  ingress:
    - from:
        - podSelector: {}  # Allows traffic from all pods in the same namespace
  policyTypes:
    - Ingress